---
- name: Filebeat installing...
  hosts: default
  gather_facts: no
  become: yes
  tasks:
    - name: Install java
      apt:
        name: default-jre
        state: present

    - name: add apt key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
        state: present
        
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes

    - name: Adding repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x

    - name: wait for conncetion
      ansible.builtin.wait_for_connection:
        timeout: 35

    - name: Install filebeat
      apt:
        name: filebeat
        state: present
        update_cache: yes
  
    - name: Remove filebeat yml file
      file: 
        path: /etc/filebeat/filebeat.yml
        state: absent

    - name: Create new Filebeat yml file
      file: 
        path: /etc/filebeat/filebeat.yml
        state: touch

    - name: adding filebeat yaml configuration
      blockinfile:
        path: /etc/filebeat/filebeat.yml
        marker: ""
        block: |
          filebeat.inputs:
          - type: log
            paths:
              - /var/log/*.log
          output.logstash:
              hosts: ["pri_ip_logstash:5044"]

    - name: Start filebeat
      service:
        name: filebeat
        state: started
        enabled: true