---
- hosts: default
  gather_facts: yes
  become: true

  tasks:
    - name: updating apt cache if needed
      become: yes
      apt:
        update_cache=yes
    
    - name: Installing Java Runtime Environment 
      become: yes
      apt:
        name: default-jre
        state: present
    
    - name: Downloading Elastic Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-amd64.deb
        dest: /tmp

    - name: Installing Elastic Deb Package
      become: yes
      apt:
        deb: /tmp/elasticsearch-7.14.0-amd64.deb
    
    - name: Updating Elasticsearch Config (IP Address)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Updating the port in config file for Elasticsearch
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'http.port:'
        line: 'http.port: 9200'

    - name: Updating Elastic Config (Node Name)
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: node-1'
      
    - name: Updating Elastic Config (Cluster Initial Master Nodes)
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'cluster.initial_master_nodes'
        line: 'cluster.initial_master_nodes: ["pri_ip_es"]'   
    
    - name: Updating Elastic Config (Discovery Seed Hosts)
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'discovery.seed_hosts'
        line: 'discovery.seed_hosts: ["pri_ip_es"]'

    - name: Starting Elasticsearch
      service:
        name: elasticsearch
        state: started
      