---
- hosts: default
  gather_facts: yes
  become: true

  tasks:
    - name: updating apt cache if needed
      become: yes
      apt:
        update_cache=yes
  
    - name: Installing Java Runtime Environment 
      become: yes
      apt:
       name: default-jre
       state: present

    - name: Downloading Filebeat Package
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.0-amd64.deb
        dest: /tmp

    - name: Installing FileBeat Deb Package
      become: yes
      apt:
        deb: /tmp/filebeat-7.17.0-amd64.deb

    - name: Removing FileBeat YAML File
      become: yes
      file:
        path: /etc/filebeat/filebeat.yml
        state: absent

    - name: Creating New FileBeat YAML File
      become: yes
      file:
          path: /etc/filebeat/filebeat.yml
          state: touch

    - name: Adding FileBeat YAML Configuration
      become: yes
      blockinfile:
          path: /etc/filebeat/filebeat.yml
          marker: ""
          block: |
            filebeat.inputs:
            - type: log
              paths:
              - /var/log/*.log
            output.logstash:
              hosts: ["localhost:5044"]
          #hosts: ["pri_ip_logstash:5044"]
    - name: Starting FileBeat Service
      become: yes
      service:
        name: filebeat
        state: started