---
- hosts: default
  gather_facts: yes

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment 
      become: yes
      apt:
       name: default-jre
       state: present

    - name: Download Kibana Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-7.6.2-amd64.deb
        dest: /tmp

    - name: Install Kibana Deb Package
      become: yes
      apt:
        deb: /tmp/kibana-7.6.2-amd64.deb
    
    - name: Update Kibana Config (IP Address)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.host'
        line: 'server.host: "0.0.0.0"'
    
    - name: Update Kibana Config (Kibana Port)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.port'
        line: 'server.port: 5601'
    
    - name: Update Kibana Config (Kibana URL)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://pri_ip_es:9200"]'
    
    - name: Start Kibana Service
      become: yes
      service:
        name: kibana
        state: started