---
- name: Kibana installing...
  hosts: default
  gather_facts: no
  become: yes
  tasks:
    - name: Install java
      apt:
        name: default-jre
        state: present

    - name: add apt key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
        state: present
        
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
 
    - name: Adding repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x
        install_python_apt: true
        update_cache: yes

    - name: wait for conncetion
      ansible.builtin.wait_for_connection:
        timeout: 35
      
    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes
        
    - name: update kibana config IP to 0.0.0.0
      lineinfile: 
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.host'
        line: 'server.host: 0.0.0.0'

    - name: update kibana config file http port to 5601
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.port'
        line: 'server.port: 5601'

    - name: update kibana config URL of elasticsearch
      lineinfile: 
        destfile: /etc/kibana/kibana.yml
        regexp: 'elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://pri_ip_es:9200"]'

    - name: Start kibana
      service: 
        name: kibana
        state: started
        enabled: true