---
- name: Logstash installing...
  hosts: default
  gather_facts: no
  become: yes
  tasks:
    - name: Install java
      apt:
        name: default-jre
        state: present

    - name: add apt key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
        state: present
        
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes

    - name: Adding repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x

    - name: wait for conncetion
      ansible.builtin.wait_for_connection:
        timeout: 35

    - name: Install logstash
      apt:
        name: logstash
        state: present
        update_cache: yes

    - name: create file main.conf for pipeline configuration
      file:
        path: /etc/logstash/conf.d/main.conf
        state: touch
        mode: u+rwx

    - name: Create logstash pipeline configuration
      blockinfile:
        path: /etc/logstash/conf.d/main.conf
        marker: ""
        block: |
          input {
            beats {
              port => 5044
            }
          }
          output {
            elasticsearch { hosts => ["pri_ip_es:9200"]}
          }

    - name: start logstash
      service: 
        name: logstash
        state: started
        enabled: true